services:
  test-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./logging.test.yml:/config/logging.test.yml
      - ./logs:/logs
    depends_on:
      - test-db
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      LOGGING_CONFIG: /config/logging.test.yml
      LOGGING_ENABLED: true
      ALEMBIC_CONFIG: /app/alembic.ini
    command: ['pytest', '-vv', 'tests/']
